package udemy.course.aws.serverless.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.io.Serializable;

/**
 * Created by raistlin on 9/13/2017.
 */
@DynamoDBTable(tableName = "compare-yourself")
public class CompareData implements Serializable {
    private static final long serialVersionUID = 1L;

    @DynamoDBHashKey(attributeName = "UserId")
    @DynamoDBAutoGeneratedKey
    private String userId;

    @DynamoDBAttribute(attributeName = "UserName")
    private String username;

    @DynamoDBVersionAttribute(attributeName = "Version")
    private Integer version;

    @DynamoDBAttribute(attributeName = "Age")
    private Integer age;

    @DynamoDBAttribute(attributeName = "Height")
    private Integer height;

    @DynamoDBAttribute(attributeName = "Income")
    private Integer income;

    public CompareData() {
    }

    public CompareData(String username, Integer age, Integer height, Integer income) {
        this.username = username;
        this.age = age;
        this.height = height;
        this.income = income;
    }

    public CompareData(String userId, Integer age, Integer height, Integer income, Integer version) {
        this.userId = userId;
        this.age = age;
        this.height = height;
        this.income = income;
        this.version = version;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public Integer getHeight() {
        return height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    public Integer getIncome() {
        return income;
    }

    public void setIncome(Integer income) {
        this.income = income;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }
}
